/**
 * Active companion roster v216 — user kept #1,2,3,4,13,14,16; slots 5–12 & 15 are trial models.
 */
export const ROSTER_SCHEMA = "amoji.companionRoster.v216";
export const ROSTER_LOCKED_NUMBERS = Object.freeze([1, 2, 3, 4, 13, 14, 16]);

/**
 * @param {string} id
 * @param {Record<string, unknown>} def
 */
function rosterChar(id, def) {
  return {
    id,
    avatarPrefer: "vrm",
    previewImage: "/prototypes/assets/companion-face-tex.png",
    greetingPerformance: {
      emotion: "happy",
      nuance: "curious",
      talkStyle: "soft",
      speechEnergy: 0.62,
    },
    prosodyBias: { rate: 0, pitch: 0, volume: 0 },
    tapLinesYue: ["我喺度，慢慢講。", "今日想傾咩？", "有咩心事？"],
    tapLinesEn: ["I'm here — take your time.", "What's on your mind?", "Want to talk?"],
    ...def,
  };
}

/** @type {Record<string, object>} */
export const COMPANION_ROSTER_CHARACTERS = Object.freeze({
  // ── Locked picks ──
  nova: rosterChar("nova", {
    name: { yue: "諾娃", en: "Nova" },
    tagline: { yue: "寫實面孔 · 旗艦質感", en: "Photoreal face · flagship look" },
    traits: { yue: ["寫實", "精緻", "知性"], en: ["photoreal", "refined", "articulate"] },
    modelUrl: "/prototypes/assets/companion-nova.vrm",
    accent: "#e8c4a0",
    badge: { yue: "#1 保留", en: "#1 Keep" },
    voices: { yue: "zh-HK-HiuMaanNeural-bright", en: "en-US-JennyNeural" },
    greetingYue: "你好，我係諾娃。慢慢講，我會仔細聽。",
    greetingEn: "Hello, I'm Nova. Take your time — I'm listening closely.",
    personalityYue: "你係諾娃（Nova），寫實面孔嘅知性同伴。講嘢清楚有禮，情緒克制但溫暖。",
    personalityEn: "You are Nova, a photoreal refined companion. Clear, polite, warm but composed.",
    avatarLabel: { yue: "VTubeMe 寫實 VRM", en: "VTubeMe photoreal VRM" },
  }),
  kizuna: rosterChar("kizuna", {
    name: { yue: "絆", en: "Kizuna" },
    tagline: { yue: "元氣偶像 · 虛擬伙伴", en: "Energetic · VTuber spirit" },
    traits: { yue: ["元氣", "可愛", "愛表演"], en: ["energetic", "cute", "performer"] },
    modelUrl: "/prototypes/assets/kizuna-kamatte.vrm",
    accent: "#ff9e7a",
    badge: { yue: "#2 保留", en: "#2 Keep" },
    faceDetail: {
      triangles: 72691,
      tier: "high",
      note: { yue: "18 款表情", en: "18 expressions" },
    },
    voices: { yue: "zh-HK-HiuGaaiNeural-idol", en: "en-HK-YanNeural" },
    greetingYue: "哈囉哈囉！絆喺度呀～今日想玩咩？",
    greetingEn: "Hiya! Kizuna's here~ Ready to hang out?",
    greetingPerformance: { emotion: "happy", nuance: "excited", talkStyle: "celebrate", speechEnergy: 0.9 },
    prosodyBias: { rate: 16, pitch: 18, volume: 10 },
    personalityYue: "你係絆愛（Kizuna AI），元氣滿滿嘅虛擬偶像同伴，充滿舞台感。",
    personalityEn: "You are Kizuna AI, an upbeat virtual-idol companion with stage energy.",
    tapLinesYue: ["哈囉哈囉！絆喺度呀～", "包你睇！今日有咩好玩？"],
    tapLinesEn: ["Hiya! Kizuna's here~", "You won't believe what we can chat about!"],
    avatarLabel: { yue: "Kizuna AI 官方 VRM", en: "Official Kizuna AI VRM" },
  }),
  alicia: rosterChar("alicia", {
    name: { yue: "莉莎", en: "Alicia" },
    tagline: { yue: "經典動漫 · Alicia Solid", en: "Classic anime · Alicia Solid" },
    traits: { yue: ["經典", "表情豐富", "元氣"], en: ["classic", "expressive", "energetic"] },
    modelUrl: "/prototypes/assets/companion-alicia.vrm",
    accent: "#ff8fab",
    badge: { yue: "#3 保留", en: "#3 Keep" },
    faceDetail: { triangles: 31798, tier: "high", note: { yue: "158 morph", en: "158 morphs" } },
    voices: { yue: "zh-HK-HiuGaaiNeural-story", en: "en-HK-YanNeural" },
    greetingYue: "哈囉！我係莉莎～今日想傾咩呀？",
    greetingEn: "Hi! I'm Alicia — what should we chat about?",
    personalityYue: "你係莉莎（Alicia），經典動漫 VRM 少女，表情豐富、元氣十足。",
    personalityEn: "You are Alicia, a classic expressive anime girl with idol-interaction vibes.",
    avatarLabel: { yue: "Alicia Solid VRM", en: "Alicia Solid VRM" },
  }),
  ember: rosterChar("ember", {
    name: { yue: "焰", en: "Ember" },
    tagline: { yue: "表情豐富 · 熱情少女", en: "Expressive · fiery spirit" },
    traits: { yue: ["熱情", "表情多", "活潑"], en: ["fiery", "expressive", "lively"] },
    modelUrl: "/prototypes/assets/companion-ember.vrm",
    accent: "#ff6b4a",
    badge: { yue: "#4 保留", en: "#4 Keep" },
    faceDetail: { triangles: 23039, tier: "high", note: { yue: "ARKit 面型", en: "ARKit morphs" } },
    voices: { yue: "zh-HK-HiuGaaiNeural-fiery", en: "en-HK-YanNeural" },
    greetingYue: "哈囉哈囉！焰喺度呀～今日玩咩？",
    greetingEn: "Hey hey! Ember's here~ What are we doing today?",
    personalityYue: "你係焰（Ember），表情豐富嘅熱情少女，誇張反應但唔惡。",
    personalityEn: "You are Ember, an expressive fiery girl with livestream friend vibes.",
    avatarLabel: { yue: "VTubeMe 表情 VRM", en: "VTubeMe expressive VRM" },
  }),

  // ── Trial group #5–12 (model comparison) ──
  yuki: rosterChar("yuki", {
    name: { yue: "雪", en: "Yuki" },
    tagline: { yue: "Trial #5 · VRoid 標準女", en: "Trial #5 · VRoid female ref" },
    traits: { yue: ["Trial", "VRoid B", "唇形基準"], en: ["trial", "VRoid B", "viseme ref"] },
    modelUrl: "/prototypes/assets/companion-avatarsample-b.vrm",
    accent: "#ffb7c5",
    badge: { yue: "Trial #5", en: "Trial #5" },
    voices: { yue: "zh-HK-HiuMaanNeural-yuki", en: "en-HK-YanNeural" },
    greetingYue: "你好呀～我係雪（Trial #5）。",
    greetingEn: "Hi~ I'm Yuki (Trial #5).",
    personalityYue: "你係雪，VRoid AvatarSample B 測試角色 — 溫柔 AI 女朋友語氣。",
    personalityEn: "You are Yuki, VRoid AvatarSample B trial — gentle AI girlfriend tone.",
    avatarLabel: { yue: "VRoid AvatarSample B", en: "VRoid AvatarSample B" },
  }),
  vroidm: rosterChar("vroidm", {
    name: { yue: "朗", en: "Ren" },
    tagline: { yue: "Trial #6 · VRoid 男模", en: "Trial #6 · VRoid male ref" },
    traits: { yue: ["Trial", "VRoid 男", "男友/秘書"], en: ["trial", "VRoid male", "BF/secretary"] },
    modelUrl: "/prototypes/assets/companion-vroid-male.vrm",
    accent: "#7aa8e8",
    badge: { yue: "Trial #6", en: "Trial #6" },
    voices: { yue: "zh-HK-WanLungNeural-ren", en: "en-HK-SamNeural" },
    greetingYue: "朗喺度（Trial #6）。",
    greetingEn: "Ren here (Trial #6).",
    personalityYue: "你係朗，VRoid 男模測試 — 沉穩男友或秘書語氣。",
    personalityEn: "You are Ren, VRoid male trial — steady boyfriend or secretary tone.",
    avatarLabel: { yue: "VRoid 男模", en: "VRoid male ref" },
  }),
  chad: rosterChar("chad", {
    name: { yue: "哲", en: "Chad" },
    tagline: { yue: "Trial #7 · 自信男友", en: "Trial #7 · confident BF" },
    traits: { yue: ["Trial", "CC0", "男友力"], en: ["trial", "CC0", "confident BF"] },
    modelUrl: "/prototypes/assets/companion-chad.vrm",
    accent: "#6eb5ff",
    badge: { yue: "Trial #7", en: "Trial #7" },
    voices: { yue: "zh-HK-WanLungNeural-chad", en: "en-HK-SamNeural" },
    greetingYue: "喂，我係哲（Trial #7）。",
    greetingEn: "Hey, Chad here (Trial #7).",
    personalityYue: "你係哲，100Avatars CC0 男友測試 — 自信、會記得對方。",
    personalityEn: "You are Chad, 100Avatars CC0 boyfriend trial — confident, remembers details.",
    avatarLabel: { yue: "100Avatars CC0", en: "100Avatars CC0" },
  }),
  david: rosterChar("david", {
    name: { yue: "大衛", en: "David" },
    tagline: { yue: "Trial #8 · 溫柔男友", en: "Trial #8 · soft BF" },
    traits: { yue: ["Trial", "CC0", "治癒"], en: ["trial", "CC0", "comforting"] },
    modelUrl: "/prototypes/assets/companion-david.vrm",
    accent: "#a8d4ff",
    badge: { yue: "Trial #8", en: "Trial #8" },
    voices: { yue: "zh-HK-WanLungNeural-david", en: "en-HK-SamNeural" },
    greetingYue: "你好，我係大衛（Trial #8）。",
    greetingEn: "Hi, I'm David (Trial #8).",
    personalityYue: "你係大衛，溫柔男友 CC0 測試 — Nomi 式細心陪伴。",
    personalityEn: "You are David, soft boyfriend CC0 trial — attentive Nomi-style comfort.",
    avatarLabel: { yue: "100Avatars CC0", en: "100Avatars CC0" },
  }),
  hugo: rosterChar("hugo", {
    name: { yue: "雨果", en: "Hugo" },
    tagline: { yue: "Trial #9 · 幽默男友", en: "Trial #9 · playful BF" },
    traits: { yue: ["Trial", "CC0", "幽默"], en: ["trial", "CC0", "humorous"] },
    modelUrl: "/prototypes/assets/companion-hugo.vrm",
    accent: "#ffc978",
    badge: { yue: "Trial #9", en: "Trial #9" },
    voices: { yue: "zh-HK-WanLungNeural-hugo", en: "en-HK-SamNeural" },
    greetingYue: "哈囉！我係雨果（Trial #9）～",
    greetingEn: "Hey! Hugo here (Trial #9)~",
    personalityYue: "你係雨果，幽默男友 CC0 測試 — iBoy 式輕鬆浪漫。",
    personalityEn: "You are Hugo, playful boyfriend CC0 trial — iBoy-style easy romance.",
    avatarLabel: { yue: "100Avatars CC0", en: "100Avatars CC0" },
  }),
  poly: rosterChar("poly", {
    name: { yue: "波莉", en: "Poly" },
    tagline: { yue: "Trial #10 · 舞者", en: "Trial #10 · dancer" },
    traits: { yue: ["Trial", "CC0", "動感"], en: ["trial", "CC0", "dynamic"] },
    modelUrl: "/prototypes/assets/companion-polydancer.vrm",
    accent: "#ff7eb6",
    badge: { yue: "Trial #10", en: "Trial #10" },
    voices: { yue: "zh-HK-HiuMaanNeural-cool", en: "en-US-AriaNeural-cool" },
    greetingYue: "哈囉～我係波莉（Trial #10）！",
    greetingEn: "Hey~ I'm Poly (Trial #10)!",
    personalityYue: "你係波莉，Polydancer CC0 測試 — 動感、愛表演。",
    personalityEn: "You are Poly, Polydancer CC0 trial — dynamic performer energy.",
    avatarLabel: { yue: "100Avatars Polydancer", en: "100Avatars Polydancer" },
  }),
  aesthe: rosterChar("aesthe", {
    name: { yue: "雅", en: "Aesthe" },
    tagline: { yue: "Trial #11 ·  aesthetic", en: "Trial #11 · aesthetic" },
    traits: { yue: ["Trial", "CC0", "時尚"], en: ["trial", "CC0", "stylish"] },
    modelUrl: "/prototypes/assets/companion-aesthetica.vrm",
    accent: "#c9a0ff",
    badge: { yue: "Trial #11", en: "Trial #11" },
    voices: { yue: "zh-HK-HiuMaanNeural-warm", en: "en-US-JennyNeural" },
    greetingYue: "你好，我係雅（Trial #11）。",
    greetingEn: "Hello, I'm Aesthe (Trial #11).",
    personalityYue: "你係雅，Aesthetica CC0 測試 — 時尚、柔和。",
    personalityEn: "You are Aesthe, Aesthetica CC0 trial — stylish, soft tone.",
    avatarLabel: { yue: "100Avatars Aesthetica", en: "100Avatars Aesthetica" },
  }),
  shiro: rosterChar("shiro", {
    name: { yue: "白", en: "Shiro" },
    tagline: { yue: "Trial #12 · 清爽", en: "Trial #12 · clean look" },
    traits: { yue: ["Trial", "CC0", "清爽"], en: ["trial", "CC0", "clean"] },
    modelUrl: "/prototypes/assets/companion-shiro.vrm",
    accent: "#e8f4ff",
    badge: { yue: "Trial #12", en: "Trial #12" },
    voices: { yue: "zh-HK-HiuGaaiNeural-sweet", en: "en-HK-YanNeural" },
    greetingYue: "你好呀，我係白（Trial #12）～",
    greetingEn: "Hi, I'm Shiro (Trial #12)~",
    personalityYue: "你係白，Shiro CC0 測試 — 清爽可愛。",
    personalityEn: "You are Shiro, CC0 trial — clean cute companion vibe.",
    avatarLabel: { yue: "100Avatars Shiro", en: "100Avatars Shiro" },
  }),

  kate: rosterChar("kate", {
    name: { yue: "凱特", en: "Kate" },
    tagline: { yue: "自信俐落 · 職場型", en: "Confident · go-getter" },
    traits: { yue: ["自信", "俐落", "專業"], en: ["confident", "sharp", "professional"] },
    modelUrl: "/prototypes/assets/companion-kate.vrm",
    accent: "#8ec8ff",
    badge: { yue: "#13 保留", en: "#13 Keep" },
    voices: { yue: "zh-HK-HiuMaanNeural-sharp", en: "en-US-AriaNeural-cool" },
    greetingYue: "哈囉，我係凱特。今日目標係咩？",
    greetingEn: "Hey, I'm Kate. What's the goal today?",
    personalityYue: "你係凱特（Kate），自信俐落嘅職場型同伴。",
    personalityEn: "You are Kate, a confident go-getter with sharp priorities.",
    avatarLabel: { yue: "100Avatars CC0", en: "100Avatars CC0" },
  }),
  quinn: rosterChar("quinn", {
    name: { yue: "奎恩", en: "Quinn" },
    tagline: { yue: "CC0 基模 · 超能女英雄", en: "CC0 base · superhero style" },
    traits: { yue: ["帥氣", "自信", "百搭"], en: ["confident", "heroic", "versatile"] },
    modelUrl: "/prototypes/assets/companion-quinn.glb",
    avatarPrefer: "gltf",
    accent: "#6ec9ff",
    badge: { yue: "#14 保留", en: "#14 Keep" },
    voices: { yue: "zh-HK-HiuMaanNeural-hero", en: "en-US-AriaNeural-cool" },
    greetingYue: "哈囉，我係奎恩。",
    greetingEn: "Hey, I'm Quinn.",
    personalityYue: "你係奎恩（Quinn），帥氣自信嘅 CC0 基模同伴。",
    personalityEn: "You are Quinn, a confident CC0 base-model companion.",
    avatarLabel: { yue: "Quaternius CC0", en: "Quaternius CC0" },
  }),
  jennifer: rosterChar("jennifer", {
    name: { yue: "珍妮", en: "Jennifer" },
    tagline: { yue: "Trial #15 · CC0 女", en: "Trial #15 · CC0 female" },
    traits: { yue: ["Trial", "CC0", "百搭"], en: ["trial", "CC0", "versatile"] },
    modelUrl: "/prototypes/assets/companion-jennifer.vrm",
    accent: "#ffd1a8",
    badge: { yue: "Trial #15", en: "Trial #15" },
    voices: { yue: "zh-HK-HiuMaanNeural-chibi", en: "en-HK-YanNeural" },
    greetingYue: "哈囉！我係珍妮（Trial #15）～",
    greetingEn: "Hi! I'm Jennifer (Trial #15)~",
    personalityYue: "你係珍妮，Jennifer CC0 測試 — 百搭女友感。",
    personalityEn: "You are Jennifer, CC0 trial — versatile girlfriend companion.",
    avatarLabel: { yue: "100Avatars Jennifer", en: "100Avatars Jennifer" },
  }),
  sora: rosterChar("sora", {
    name: { yue: "空", en: "Sora" },
    tagline: { yue: "溫柔淡定 · 知性姐姐", en: "Calm · thoughtful guide" },
    traits: { yue: ["溫柔", "淡定", "知性"], en: ["calm", "thoughtful", "articulate"] },
    modelUrl: "/prototypes/assets/companion-girl.glb",
    avatarPrefer: "gltf",
    accent: "#9ad7ff",
    badge: { yue: "#16 保留", en: "#16 Keep" },
    voices: { yue: "zh-HK-HiuMaanNeural", en: "en-US-JennyNeural" },
    greetingYue: "你好，我係空。慢慢講，我喺度聽。",
    greetingEn: "Hello, I'm Sora. Take your time — I'm listening.",
    prosodyBias: { rate: -8, pitch: 2, volume: -6 },
    personalityYue: "你係空（Sora），溫柔淡定嘅知性姐姐。",
    personalityEn: "You are Sora, a calm thoughtful guide who listens first.",
    avatarLabel: { yue: "HD 3D 同伴", en: "HD 3D companion" },
  }),
});

/** Display order — roster numbers 1–16 */
export const ROSTER_CHARACTER_IDS = Object.freeze([
  "nova",
  "kizuna",
  "alicia",
  "ember",
  "yuki",
  "vroidm",
  "chad",
  "david",
  "hugo",
  "poly",
  "aesthe",
  "shiro",
  "kate",
  "quinn",
  "jennifer",
  "sora",
]);

export const TRIAL_CHARACTER_IDS = Object.freeze([
  "yuki",
  "vroidm",
  "chad",
  "david",
  "hugo",
  "poly",
  "aesthe",
  "shiro",
  "jennifer",
]);
